### ISSUE TITLE
IndexError for xa.aggregate(ds, weightmap)

### ISSUE THREAD

**Issue by realseqi** [ks905383/xagg_archived#11]
I followed the two lines code structure. It successfully gets the weightemap. However, when I use the code xa.aggregate(ds, weightmap) to aggregate, I have the below errors. Could you help me to check what's happening here?

~/opt/anaconda3/lib/python3.8/site-packages/xagg/core.py in aggregate(ds, wm)
    406                         # Replace overlapping pixel areas with nans if the corresponding pixel
    407                         # is only composed of nans
--> 408                         tmp_areas[np.array(np.isnan(ds[var].isel(loc=wm.agg.iloc[poly_idx,:].pix_idxs)).all(other_dims).values)] = np.nan
    409                         # Calculate the normalized area+weight of each pixel (taking into account
    410                         # nans)

IndexError: too many indices for array: array is 0-dimensional, but 1 were index

**Comment by ks905383** [comment]
Hi @realseqi, apologize for the issue (and for the late reply!). Looks like it happens when a polygon is covered by only one pixel. I managed to fix it in the test version so far (through making sure the relevant variable was run through `np.atleast_1d()`), which you can access through: 

`pip install -i https://test.pypi.org/simple/ xagg==0.2.4`

I'm aiming to have the full version of this up within a day or two.

**Comment by ks905383** [comment]
Ok, should be fixed with `xagg 0.2.4`. NB: I've moved all the code over to a fresh repo for reasons of getting rid of a bunch of junk - for future issues, please head over to https://github.com/ks905383/xagg. (`pip install xagg` should work as normal though)
