### ISSUE TITLE
Make explicit assumption that dimensions are named `lon` and `lat`

### ISSUE THREAD

**Issue by jrising** [ks905383/xagg_archived#8]
I have a NetCDF with dimensions called `longitude` and `latitude`. Interestingly, the `pixel_overlaps` function succeeds on the dataset, but when I call `aggregate` I get a `KeyError: 'lat'`.

Everything works as expected if I call `xr.rename()` to switch my dimensions to `lon` and `lat`.

I think that both of these functions should fail gracefully, with a helpful message about the expected names of the latitude and longitude dimensions.

**Comment by ks905383** [comment]
Oh interesting - what's _supposed_ to happen is that the core/wrapper functions should actually all be calling `xa.fix_ds()` if they're working with raw dataset inputs, which should in theory fix the names of dimensions, as long as they're called one of like 10 things I've seen out in the wild. 

Could you give me a reproducible example? 

Longer term, it seems that there's an effort by others to create a robust tool to fix all the naming conventions (`cf_xarray` I believe), so I'm writing a note here to remind myself to keep an eye out for that development, and potentially integrate it.

(NB: I'm currently working on completely revamping `xagg` to be robust, documented, and tested - hopefully should be able to release it in a few weeks. Some bugs are going to only be fixed once that new version gets released)

**Comment by jrising** [comment]
Sorry for all of the issues today! My use case really is super-simple, or so I thought.

Data and code for the example are now reference in the most recent issue too:
https://www.dropbox.com/sh/d4iba44mrfbpc7d/AABxheu2_TXyNKEPIlZU4PXka?dl=0

Code in `state-sst.py`. Drop the `ds = ds.rename(dict(longitude='lon', latitude='lat'))` line to get the error.

**Comment by ks905383** [comment]
No absolutely - this is exactly the kind of reports I want from any 'field testing'.

Found the issue. `xa.aggregate()` should also have `ds = xa.fix_ds(ds)` right at the start, to take the semantic differences into account. I think in some of my own testing I've just been doing `ds = xa.fix_ds(ds)` _before_ running the rest of the code, which is *not* how I intend for this to work. The code should be doing that behind the scenes. 

This will definitely be fixed with the next major update (coming up soon) - up until then I recommend adding `ds = xa.fix_ds(ds)` to your workflow, which should fix this issue.

**Comment by jrising** [comment]
Great, thanks for the fix!

**Comment by ks905383** [comment]
Should be fixed with `0.1.4` which is now live.
